### ISSUE TITLE
Xiaomi Honeywell smoke detector

### ISSUE THREAD

**Issue by Thomas1305** [dresden-elektronik/phoscon-app-beta#111]
Hi there,

will the Xiaomi honeywell smoke detector be supported in future? [https://de.gearbest.com/alarm-systems/pp_615081.html](url)
If i pair it in the phoscon app, it´s not shown in the device list. 
But in iobroker at the objects-tab it´s shown.
Why?
Please integrate it in the phoscon app too.
It would be greate.

**Comment by YKO-de** [comment]
Problem should be fixed by now.

**Comment by thelefty** [comment]
Mine still doesn't show in the Phoscon UI. Is that what you fixed?

**Comment by GitGabKat** [comment]
I would also appreciate if deconz would support Xiaomi Smoke Detector in the future. Due to zigbee connectivity it should work generally.
