### ISSUE TITLE
Please add Heiman HS1CA-E Carbon Monoxide Detector

### ISSUE THREAD

**Issue by robroll** [dresden-elektronik/phoscon-app-beta#117]
Hello Dresden-Elektronik team,
Please add support for the Heiman HS1CA-E Carbon Monoxide Detector.
Many thanks,
Rob

<img width="891" alt="Screenshot 2019-06-04 at 00 03 52" src="https://user-images.githubusercontent.com/51242313/58840284-f1010580-865c-11e9-911f-15b746b2733e.png">

**Comment by YKO-de** [comment]
Problem should be solved by now. If not, reopen issue.

**Comment by pattyland** [comment]
@YKO-de So at least in 2.05.77 I don't see my HS1CA sensor.
As there are no commits in this repository I can't tell if something changed?

**Comment by pattyland** [comment]
Upgraded to 2.05.78 and the HS1CA is still not visible in Phoscon

**Comment by Mimiix** [comment]
Re-opened as per request of @pattyland .

**Comment by YKO-de** [comment]
I found the error. It should work with the next release. 
I'll update the beta tomorrow. Then you could test it there.

**Comment by pattyland** [comment]
I can see my Heiman HS1CA-E sensor in the current beta

I'm not sure how to identify the Phoscon version, is it the date behind the deCONZ version? If yes I testet with v21.7.2020

**Comment by YKO-de** [comment]
In the meantime, the sensor should also function quite normally in the pwa. Therefore I would close the issue now.

**Comment by GitHubxtsnl** [comment]
I'm having the same issue.
I'm running Home Assistant 2021.2.3
deCONZ 6.7.0
ConBee II 26660700 / 2.09.03 / 12/23/2020

I've got this CO device from Ali:
https://www.aliexpress.com/item/4001031100655.html?spm=a2g0s.9042311.0.0.6da04c4dTuT4Ht

![image](https://user-images.githubusercontent.com/43134674/107992807-c3e3ba80-6fd9-11eb-8388-64fc2303c0e1.png)

![image](https://user-images.githubusercontent.com/43134674/107992821-cc3bf580-6fd9-11eb-90db-98a0122db479.png)

![image](https://user-images.githubusercontent.com/43134674/107992828-d1994000-6fd9-11eb-9e6d-a24b46c717be.png)

I can see it is connected, the green line, but I cannot change the Node name nor does it come up in HA.
I think it is not supported yet by deCONZ / ConBee

any ideas or suggestions on how to get this device working?

**Comment by Mimiix** [comment]
Seems to be unsupported. You should open a device request.
