### ISSUE TITLE
no Menue Bar

### ISSUE THREAD

**Issue by burreo** [dresden-elektronik/phoscon-app-beta#250]
I am using the raspbee 2 and installed it on my openhabian.
The software install was also working well according to
https://community.openhab.org/t/phoscon-deconz-on-openhabian/85030/3
I set the port to 19090
If I open http://192.168.178.43:19090/
and setting the default password, I cannot get into the menue.
For a microsecond I see the menue on the left but then an
Error message shows up:
Network was not found...
![image](https://user-images.githubusercontent.com/20820902/99722677-45967b80-2ab1-11eb-964b-3e2d853b71b5.png)

The only link points back to the login page.
How can I unlock without being able to navigate to the menue?

**Comment by chlctt** [comment]
I do have the same problem using ConBee II. I just received the above message after restarting the Gateway from the GUI. The restart was considered to reconnect on IKEA Tradfri Remote Control that wasn't sending any triggers anymore.

**Comment by burreo** [comment]
I just downgraded to 2.5.88 and now the phoscon app is working fine.
@chlctt Does this work for you as well?

**Comment by Ajowan84** [comment]
Same problem with 2.06.00 version...

**Comment by artiomchi** [comment]
Running this on a docker container with a ConBee II attached as a volume from /dev/

This was working perfectly fine for over a year, with me updating the container from time to time.
A recent update seems to have broken it - I have to restart the container several times a day, otherwise I get the same error as in the OP

**Comment by eric1905** [comment]
I have the same problem. How can I downgrade to 2.5.88 ?

**Comment by StefanCohen** [comment]
Just updated to the latest version via apt and got the same issue on an RPi. Tried to install it on another machine running Ubuntu 20.04 but the result was the same. The API still works so I assume this is some UI glitch.

**Comment by watho** [comment]
Same problem with 2.07.01-debian-buster-stable. Downgrade to 2.05.86 from [here](http://deconz.dresden-elektronik.de/ubuntu/beta/) solves the issue.

**Comment by YKO-de** [comment]
The problem should be fixed with the next update.

**Comment by StefanCohen** [comment]
I tried the 2.08.00 beta on Ubuntu but with no luck. The problem persists for me.
