### ISSUE TITLE
Lidl LivarnoLux Remote

### ISSUE THREAD

**Issue by Heiner1967** [dresden-elektronik/phoscon-app-beta#315]
**Describe the bug**
Hi, i bought some LavarnoLux LED Light pannels including a remote from Lidl.
Those could be introduced to Phoscom in the following steps:

Now the light works with colour adaption and brightness adaption via phoscon, the remote works as well but only for on/off and brightness. The color selection is not working. However no remote is shown inside phoscon.

If however I reset the pannel and the remote, and only connect remote to the pannel, i can on top choose in between of 4 colours.

To note the Pannel is shown in phoscon as from Vendor Heiman and Model TS0502A

**Steps to reproduce the behavior**

reset the remote and put into coupling mode, search in phoscom for new lights - it looks like no result, but no worries.
power the light pannel, which blinks to indicate to be in couplng mode, search for lights again, phoscom add a new device.
put the remote in couplingmode again, and the light confirm it works.
If the problem can't be reproduced and is sporadic, please provide some details
on how often and when the issue happens.

**Expected behavior**
The remote should be visible in phoscon like a Philips Dim Switsh
the remote should be able to change color by repeating to push the "1" buttom.

**Environment**
Host system: Raspberry Pi
Running method: Raspbian / fhem
Firmware version: 26660700
Phoscon version: 2.05.84
Device: ConBee II
Do you use an USB extension cable: no
Is there any other USB or serial devices connected to the host system? No

**Comment by mrschweizer** [comment]
Hi,
I'm using a Conbee ii with home-assistant and the dezcon integration. I'm also having some trouble with the Lidl remote (Livarno Lux, 334437_1910, FB20-002) from end 2020/beginning 2021.
When trying to pair it as a switch, it doesn't show up. Apparently there are different pairing modes, but none of them shows up in Phoscon.
However, I realized, that home assistant registers it as a device. Pressing the buttons is also registered as event. Different buttons with different IDs.
So far so good. The only problem is, that despite not showing them as remote, either dezcon or phoscon seem to react on the button presses, switching the state of all other dezcon devices, whithout actually changing it. Meaning the physical state of the lamps is not affected by this, only the state in the phoscon api.
The change of state is shown in phoscon immediately and in home assistant with some delay. This is why I'm pretty sure that the behaviour originates in phoscon or dezcon.

Maybe someone can confirm this behaviour. I'm fairly new to Github, so please be patient with me for the form of the contribution.

Thanks and Cheers

**Comment by achimlo** [comment]
I have the same behaviour as described above by mrschweizer

**Comment by achimlo** [comment]
No, my remote is the one described above, it has only 4 buttons

**Comment by mrschweizer** [comment]
Same for me.

> No, my remote is the one described above, it has only 4 buttons. It looks like this
> ![image](https://user-images.githubusercontent.com/78682771/107639651-7382fa80-6c71-11eb-8700-af7897d9dc1d.png)

**Comment by mrschweizer** [comment]
I read something lately about _a_ remote automatically broadcasting to the whole group it is assigned to. I think in that thread the issue could be solved by automatically creating a new, empty group when connecting. I know this is very vague. Unfortuantely I did not manage to find that thread again. I'm sorry for that.

Cheers,
Matthias

**Comment by lucky2k12** [comment]
The remote should be identical to the one in this issue: https://github.com/dresden-elektronik/phoscon-app-beta/issues/284

**Comment by Heiner1967** [comment]
> No, my remote is the one described above, it has only 4 buttons. It looks like this
> ![image](https://user-images.githubusercontent.com/78682771/107639651-7382fa80-6c71-11eb-8700-af7897d9dc1d.png)

same for me

**Comment by jeffrey-zammit** [comment]
Same here. Any solutions?

**Comment by achimlo** [comment]
There is still no solution for the described issue. Would be happy to see someone working on it

**Comment by SEK-DE** [comment]
We´re on it.

**Comment by SEK-DE** [comment]
Lidl Livarno Remote is integrated in our beta now! 
Check out http://phoscon.de/pwabeta
go to the switch beta there. All events should work properly.
Let us know if there are further issues.
This will be implemented in one of the future updates if you dont want to use the beta.

**Comment by lucky2k12** [comment]
Thank you, the events of all buttons are working fine. 
But I don't get the remote listed when trying binding to a light group in the switch editor. 
There are only my xiaomi smart switches, though I deleted and coupled the Lidl remote again.

**Comment by SEK-DE** [comment]
@lucky2k12 you use definately the Beta? It works in our setup (beta only) well so far.

**Comment by lucky2k12** [comment]
Yes, i am using the Beta. The remotes do not appear in the switches menu in the release version.

**Comment by SEK-DE** [comment]
it should look like this:
![image](https://user-images.githubusercontent.com/80257288/121311604-dbd2a780-c904-11eb-89f2-288d59c79db8.png)
check your deCONZ and Firmware please.

**Comment by lucky2k12** [comment]
Thank you!

Yes, that is what I see here too. But in the Switch Editor the Lidl remote does not show up:
![image](https://user-images.githubusercontent.com/68598627/121321964-d9754b00-c90e-11eb-815c-2f227c7fff18.png)
deconz version is 2.12.00
Firmware 26680700 (should i update to the latest FW?)
![image](https://user-images.githubusercontent.com/68598627/121322862-a089a600-c90f-11eb-8ba4-4cc801a4bf2b.png)

**Comment by SEK-DE** [comment]
Problem is, the second button from above triggers multiple events if you hold it. That makes a integration in the switch editior impossible at the moment. Our main programmer will take a look on this special problem. I will give you feedback asap.

**Comment by SEK-DE** [comment]
Problem is solved! Watch out for the next deCONZ update, the solution will be included. I let this issue open until a couple of days after the next release. So if you have further troubles with it, post it here.

**Comment by mrschweizer** [comment]
I'm having trouble to access the beta version of phoscon on my home-assistant installation.
When I try to login in the beta version I get a failed error. The password should definitely be right.

**Comment by mkashwin** [comment]
Is there a date for the release of the update?
I am currently on Version 2.11.05 / 09/05/2021
firmware 26660700
and it claims to be the latest version (but obviously doesn't have your latest patch)

**Comment by SEK-DE** [comment]
@mkashwin it will be released when it´s done, can´t say nothing more to this topic.
Do you use a HA System? Otherwise you can update your system already. 
Here is a complete manual: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually
Please go for both, Firmware and deCONZ.

**Comment by mkashwin** [comment]
> @mkashwin it will be released when it´s done, can´t say nothing more to this topic.
> Do you use a HA System? Otherwise you can update your system already.
> Here is a complete manual: https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually
> Please go for both, Firmware and deCONZ.

Thanks. 
I am in Home Assistant so will probably have to wait for the update.

**Comment by vmercep** [comment]
do we have any updates on this one. I have a problem that switch is deconz but when I press on/off button all lights in devices are switched to ON state, not phisicaly ( they are off) but in app all lights like they are ON.

**Comment by mrschweizer** [comment]
> do we have any updates on this one. I have a problem that switch is deconz but when I press on/off button all lights in devices are switched to ON state, not phisicaly ( they are off) but in app all lights like they are ON.


The home assistant addon deconz 6.10.0 bumps phoscon v2.12.6 [This](https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.12.6).  This should also include  some changes in [v2.12.4](https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.12.1-beta):

> LIDL Livarno Lux remote, button names, rules on config/on #5005

I didn't find the time to do the update yet.

**Comment by mrschweizer** [comment]
Just did the update. It works in my configuration. I can read single press events for 0 and 1 button, as well as single press, hold and release for "brighter" and "dimm" buttons.

**Comment by vmercep** [comment]
when can we expect release? I have 2.12.06 / 8/19/2021 version and switch is there and working properly, but this is annoying when all lights in app goes ON and that reflects domoticz so I don't know which is on and which is off.

**Comment by vmercep** [comment]
> Just did the update. It works in my configuration. I can read single press events for 0 and 1 button, as well as single press, hold and release for "brighter" and "dimm" buttons. The weird grouping with phantom state switching is fixed.

did you push your change? will we have fix for this issue in next release?

**Comment by JerroldAI** [comment]
> Just did the update. It works in my configuration. I can read single press events for 0 and 1 button, as well as single press, hold and release for "brighter" and "dimm" buttons. The weird grouping with phantom state switching is fixed.

How exactly did you fix the phantom switching? On 6.10 but still having the same issues as @vmercep, on/off switches all my lights in Phoscon/HA without actually turning them on/off.

**Comment by vmercep** [comment]
> How exactly did you fix the phantom switching @mrschweizer? On 6.10/2.12.6 but still having the same issues as @vmercep, on/off switches all my lights in Phoscon/HA without actually turning them on/off.

he fixed it locally, I think code is not pushed to master. Yes problem still occurs and can someone fix this issue?

**Comment by mrschweizer** [comment]
> Problem is solved! Watch out for the next deCONZ update, the solution will be included. I let this issue open until a couple of days after the next release. So if you have further troubles with it, post it here.

For me it was fixed with the update that @SEK-DE  referenced. As @mkashwin  I had to wait for the deconz update in the Home Assistant deconz addon. My issue is fixed in master since August. At the moment I am using Home Assistant Deconz Addon 6.10.0. This uses deCONZ to 2.12.6. I'm using both from the shelf, no code changes from my side. I just wanted to confirm the fix. I thought the issue was closed.

**Comment by vmercep** [comment]
> For me it was fixed with the update that @SEK-DE referenced. As @mkashwin I had to wait for the deconz update in the Home Assistant deconz addon. My issue is fixed in master since August. At the moment I am using Home Assistant Deconz Addon 6.10.0. This uses deCONZ to 2.12.6. I'm using both from the shelf, no code changes from my side. I just wanted to confirm the fix. I thought the issue was closed.

Still same issue, I have tryed deconz 2.13.2 and same thing is happening.

**Comment by JerroldAI** [comment]
Still have the phantom switching issue. Pairing the remote works, but after pairing pressing the on button leads to marking all my lights as on, without actually turning them on. I am on Deconz 2.12.6, running within HA integration 6.10. @SEK-DE, do you know a way to manually disbable the broadcast on/off & phantom switching?

**Comment by vmercep** [comment]
Still same issue, 2.13.4 deconz version.
